function trial_ = extract_trial_contineous_data (trial, continueous_data, continueous_data_time, x_low_lim, x_high_lim)
    time_on_set = trial.Time_Onset_PHDI+30;
    trial_.continueous_data.info = continueous_data( ...
                        continueous_data_time > time_on_set + x_low_lim & ...
                        continueous_data_time < time_on_set + x_high_lim ...
    );
    trial_.continueous_data.time = continueous_data_time( ...
                        continueous_data_time > time_on_set + x_low_lim & ...
                        continueous_data_time < time_on_set + x_high_lim) ...
                        - time_on_set ....
    ;
    trial_.filtered_data = lowpass( ...
                        trial_.continueous_data.info, ...
                        250, ...
                        30000 ...
    );
end
