function plot_lfp_sparse_noise ( ...
            continueous_data, ...
            continueous_data_time, ...
            trials, ...
            x_low_lim, ...
            x_high_lim, ...
            x_axis_partitions ...
        )
    continueous_data = double(continueous_data);
    min_len = 1000000;
    trials_ = struct('continueous_data', {}, 'filtered_data', {});
    for i = 1:numel(trials)
        trials_(i) = extract_trial_contineous_data( ...
                            trials(i), ...
                            continueous_data, ...
                            continueous_data_time, ...
                            x_low_lim, ...
                            x_high_lim ...
        );
        min_len = min(min_len, numel(trials_(i).filtered_data));
    end

    lfp = zeros(1, min_len);
    for i = 1:numel(trials_)
        lfp = lfp + trials_(i).filtered_data(1:min_len);
    end
    lfp = lfp ./ numel(trials_);
    lfp = smooth(lfp, 100);
    plot(trials_(1).continueous_data.time(1:min_len), lfp, 'b');
end
